import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: ["todo", "resources"],
  frontendSidebar: [
    "Frontend/intro",
    {
      type: "category",
      label: "Computer Science",
      items: [
        "Frontend/Computer-Science/how-the-internet-works",
        "Frontend/Computer-Science/early-programming",
        "Frontend/Computer-Science/Algorithms",
        "Frontend/Computer-Science/computer-science",
      ],
    },
    {
      type: "category",
      label: "The Basics",
      items: ["Frontend/HTML-CSS/HTML", "Frontend/HTML-CSS/CSS"],
    },

    {
      type: "category",
      label: "Adding APIs & Backend",
      items: [
        "Frontend/APIs/APIs",
        "Frontend/APIs/GraphQL",
        "Backend/NodeJS/NodeJS",
      ],
    },
    {
      type: "category",
      label: "Frameworks",
      items: ["Frontend/React/React", "Frontend/NextJS/NextJS"],
    },

    // {
    //   type: "category",
    //   label: "Clean Code",
    //   items: [],
    // },
    {
      type: "category",
      label: "Advanced Styling",
      items: ["Frontend/HTML-CSS/TailwindCSS", "Frontend/HTML-CSS/SASS"],
    },
  ],
  backendSidebar: [
    {
      type: "category",
      label: "Cloud Infrastructure",
      items: ["Backend/Cloud/Cloud"],
    },
  ],
  cyberSidebar: ["Cybersecurity/Books", "Cybersecurity/Courses"],
  // leadershipSidebar: ["Cybersecurity/Books", "Cybersecurity/Courses"], // ace interviews, manage people, kindness
};

export default sidebars;
