import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually


  frontendSidebar: [

  
    
    "Topics/HTML-CSS/HTML/HTML",
    "Topics/HTML-CSS/CSS/CSS/CSS",
    
    
    "Topics/Javascript/Javascript",
    
    "Topics/Tools/VSCode",
    "Topics/Node/npm/npm",

   

    
  
{
      type: "category",
      label: "Git ⭐️",
      items: [      

   "Topics/Git/Git/Git",
    "Topics/Git/Github/Github",],
    },

     


        "Topics/Computer-Science/Basics",


  {
      type: "category",
      label: "APIs 🛜",
      items: [      

   "Topics/APIs/APIs",
    "Topics/APIs/GraphQL",],
    },

    "Topics/React/React",



     {
      type: "category",
      label: "Node 🖼️",
      items: [   "Topics/Node/NodeJS/NodeJS",
            "Topics/Node/npm/npm",],
    },

    "Topics/Tools/Dev-Tools",

            {
      type: "category",
      label: "Terminal, OS 🎮",
      items: ["Topics/Terminal/BASH", "Topics/Terminal/Operating-System"],
    },

      {
      type: "category",
      label: "React Frameworks ⚙️",
      items: [      

    "Topics/NextJS/NextJS",     "Topics/Qwik/Qwik",],
    },



    

        {
      type: "category",
      label: "Advanced Styling 🎨",
      items: [      
    "Topics/HTML-CSS/CSS/Animations/Animations",
    "Topics/HTML-CSS/CSS/TailwindCSS/TailwindCSS",
    "Topics/HTML-CSS/CSS/SASS",],
    },


     {
      type: "category",
      label: "Design 🖼️",
      items: [ "Topics/Design/UI/UI",
          "Topics/Design/UX/UX",],
    },
  



     
    


        

            {
      type: "category",
      label: "Cloud Computing ☁️",
      items: ["Topics/Cloud/Cloud/Cloud", "Topics/Cloud/Docker/Docker"],
    },

  "Topics/Architecture/Architecture",
  
  

    "Topics/AI/AI",
    


  

  
   
  // {
  //     type: "category",
  //     label: "Clean Code",
  //     items: [],
  //   },
   

 
 

    

   "Topics/Cybersecurity/Courses",
    
  ],

    componentsSidebar: [

   
    "Components/HorizontalScroll/HorizontalScroll"

    
  

]

  // projectSidebar: [

  //    {
  //     type: "category",
  //     label: "Test yourself",
  //     items: ["Projects/Challenges"],
  //   },
  //   "Projects/Marketplace"

    
  // ],
  
};

export default sidebars;
